name: android_build

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          pnpm install
          pnpm install -g cordova
      - name: Build for fontend
        run: |
          pnpm run build
      - name: Build for debug
        run: |
          ls
          cordova platform add android
          cordova build android
      - name: Upload app-debug.apk
        uses: actions/upload-artifact@v2 
        with:
          name: app-debug.apk
          path: ./platforms/android/app/build/outputs/apk/debug
      - name: build for release
        run: |
          cordova build android --release --prod -- --packageType=apk
          ls platforms/android/app/build/outputs/
      - name: Upload android-release-unsigned.apk
        uses: actions/upload-artifact@v2 
        with:
          name: android-release-unsigned.apk
          path: ./platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk

  signApp:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download artifacts from build job
        uses: actions/download-artifact@v2
        with:
          name: android-release-unsigned.apk
          path: path/to/artifacts
      - name: Sign the APK
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: path/to/artifacts/
          signingKeyBase64: ${{ secrets.SIGNING_KEY_BASE64 }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload signed APK
        uses: actions/upload-artifact@v2
        with:
          name: signed-apk
          path: path/to/artifacts/app-release-unsigned-signed.apk

      - name: test
        run: |
         cd path/to/artifacts/
         ls
        
